---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: .

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.package:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts['os_family'] == 'Debian'
      changed_when: false

  vars:
    php_packages:
      - "php{{php_default_version_debian}}"
